name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker Image
      id: build-image
      run: |
        ECR_REGISTRY=$(aws ecr describe-repositories --repository-names news-search-agent --query "repositories[0].repositoryUri" --output text)
        
        docker build -t $ECR_REGISTRY:latest .
        docker push $ECR_REGISTRY:latest
        
        echo "ECR_URI=$ECR_REGISTRY:latest" >> $GITHUB_ENV

    - name: Deploy to AWS App Runner
      run: |
        SERVICE_ARN=$(aws apprunner list-services --query "ServiceSummaryList[?ServiceName=='news-search-service'].ServiceArn" --output text)

        if [ -z "$SERVICE_ARN" ]; then
          echo "Creating new AWS App Runner service..."
          aws apprunner create-service --service-name news-search-service --source-configuration file://apprunner-source.json
        else
          echo "Updating existing AWS App Runner service..."
          aws apprunner update-service --service-arn $SERVICE_ARN --source-configuration file://apprunner-source.json
        fi
